import { useEffect, useMemo } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { burst, backdrop, ease, dur } from '../motion'
import Confetti from './ui/Confetti'
import Icon from './ui/Icon'

// ── Rank-up intensity tiers ─────────────────────────────────────────────
// tier=1: normal (Cadet → Pilot etc.) — quick, light celebration
// tier=2: major  (mid ranks like Lieutenant → Captain) — more rays + confetti
// tier=3: legendary (high ranks → Admiral / Star Admiral) — full cinematic
//
// Callers either pass `tier` directly, or we infer it from rank.next_name
// being null (top-of-ladder = legendary) or from xp_next size.
const TIER_CFG = {
  1: { rays: 10, confetti: 70,  sparkles: 18, pulseRings: 2, buildup: 0.0, label: 'Rank Up' },
  2: { rays: 14, confetti: 130, sparkles: 28, pulseRings: 3, buildup: 0.4, label: 'Rank Up' },
  3: { rays: 18, confetti: 200, sparkles: 40, pulseRings: 4, buildup: 0.8, label: 'Legendary Rank Up' },
}

function inferTier(newRank, explicit) {
  if (explicit) return Math.max(1, Math.min(3, explicit))
  // Top of the ladder = always legendary
  if (!newRank?.next_name) return 3
  // xp_next as a rough indicator of tier height
  const xp = newRank?.xp_next || 0
  if (xp >= 5000) return 3
  if (xp >= 1500) return 2
  return 1
}

/**
 * Full-screen RANK UP celebration. Build-up + intensity scales with tier.
 *
 * Props:
 *   newRank:   { name | tier_name, icon | tier_icon, next_name, xp_next }
 *   tier:      1 | 2 | 3   (optional; inferred from rank if omitted)
 *   onDismiss: () => void
 */
export default function RankUpOverlay({ newRank, tier: tierProp, onDismiss }) {
  useEffect(() => {
    const prev = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = prev }
  }, [])

  const tier = inferTier(newRank, tierProp)
  const cfg  = TIER_CFG[tier]

  const name = newRank?.name || newRank?.tier_name || 'New rank'
  const icon = newRank?.icon || newRank?.tier_icon || '⭐'
  const nextName = newRank?.next_name
  const xpNext = newRank?.xp_next

  const accent = '#fbbf24'
  const glow = '0 0 30px rgba(251, 191, 36, 0.7), 0 0 90px rgba(192, 132, 252, 0.45)'

  // ── Sunburst rays — every ray must avoid the four cardinal directions
  //    (0/90/180/270) by at least 8° so no two opposite rays form a
  //    perfectly vertical or horizontal line. Generated by stepping
  //    evenly, then nudging any cardinal-adjacent angle a few degrees
  //    off. The resulting layout still LOOKS symmetric but breaks the
  //    "single line" optical artifact. ──
  const rays = useMemo(() => {
    const step = 360 / cfg.rays
    const offset = step / 2
    const cardinals = [0, 90, 180, 270, 360]
    return Array.from({ length: cfg.rays }, (_, i) => {
      let a = (offset + i * step) % 360
      // Nudge if too close to any cardinal — keeps rays distinct lines
      for (const c of cardinals) {
        if (Math.abs(a - c) < 8) a = (c + (a < c ? -8 : 8) + 360) % 360
      }
      return { angle: a, delay: cfg.buildup + i * 0.025 }
    })
  }, [cfg.rays, cfg.buildup])

  const sparkleColors = ['#fbbf24', '#fb923c', '#c084fc', '#e879f9', '#38bdf8', '#a3e635', '#ffffff']
  const sparkles = useMemo(() => Array.from({ length: cfg.sparkles }, (_, i) => ({
    id: i,
    left: 5 + Math.random() * 90,
    top:  8 + Math.random() * 65,
    delay: cfg.buildup + Math.random() * 0.8,
    duration: 1.4 + Math.random() * 1.2,
    size: 14 + Math.random() * 22,
    color: sparkleColors[i % sparkleColors.length],
  })), [cfg.sparkles, cfg.buildup])

  return (
    <AnimatePresence>
      <motion.div
        key="rankup-overlay"
        onClick={onDismiss}
        className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md overflow-hidden"
        variants={backdrop}
        initial="initial"
        animate="animate"
        exit="exit"
      >
        {/* Spotlight — radial glow lighting up the stage */}
        <motion.div
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
              'radial-gradient(circle at center, rgba(251,191,36,0.32) 0%, rgba(192,132,252,0.18) 30%, transparent 65%)',
          }}
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{
            opacity: [0, 1, 0.85],
            scale:   [0.5, 1.1, 1],
            transition: { duration: 0.9 + tier * 0.2, ease: ease.out, delay: 0.05 },
          }}
        />

        {/* Anticipation pre-pulse for tier ≥ 2 — a single faint flash that
            sets up the main burst, building suspense before the icon hits. */}
        {tier >= 2 && (
          <motion.div
            className="absolute inset-0 pointer-events-none"
            style={{ background: 'radial-gradient(circle at center, rgba(255,255,255,0.18) 0%, transparent 40%)' }}
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{
              opacity: [0, 0.7, 0],
              scale:   [0.5, 1.4, 1.8],
              transition: { duration: cfg.buildup + 0.4, ease: ease.out },
            }}
          />
        )}

        {/* (Rays + pulse rings used to live here, centred on the viewport.
            They've moved INSIDE the icon container in the cascade below
            so they radiate from the actual icon position regardless of
            how much text sits above or below it.) */}

        {/* Confetti — count scales with tier */}
        <Confetti
          count={cfg.confetti}
          duration={4.2 + tier * 0.3}
          colors={['#fbbf24', '#fb923c', '#c084fc', '#e879f9', '#a3e635', '#ffffff', '#38bdf8']}
          shape="rect"
        />

        {/* Glitter sparkles */}
        {sparkles.map((s) => (
          <motion.span
            key={`spk-${s.id}`}
            className="pointer-events-none absolute select-none"
            style={{
              left: `${s.left}%`,
              top:  `${s.top}%`,
              fontSize: s.size,
              color: s.color,
              textShadow: `0 0 12px ${s.color}`,
            }}
            initial={{ opacity: 0, scale: 0, rotate: 0 }}
            animate={{
              opacity: [0, 1, 1, 0],
              scale:   [0, 1, 0.85, 0],
              rotate:  [0, 180, 360],
              transition: {
                duration: s.duration,
                delay: s.delay,
                ease: ease.loop,
                repeat: Infinity,
                repeatDelay: 0.6,
              },
            }}
          ><Icon name="sparkle" style={{ width: s.size, height: s.size }} /></motion.span>
        ))}

        {/* TOP REGION — banners above the icon. Anchored to the viewport
            so its bottom edge sits just above the icon's top edge,
            regardless of how many lines of text it contains. */}
        <motion.div
          onClick={(e) => e.stopPropagation()}
          className="absolute left-0 right-0 text-center px-6 z-10 pointer-events-none"
          style={{ bottom: '50%', marginBottom: 120 }}
        >
          {/* Anticipation line for tier ≥ 2 */}
          {tier >= 2 && (
            <motion.div
              className="font-black uppercase tracking-[0.5em] mb-2 select-none"
              style={{
                color: 'rgba(255,255,255,0.85)',
                fontSize: tier === 3 ? 13 : 11,
                textShadow: '0 0 14px rgba(251,191,36,0.7)',
              }}
              initial={{ opacity: 0, letterSpacing: '0.2em' }}
              animate={{
                opacity: [0, 1, 1, 0.6],
                letterSpacing: ['0.2em', '0.6em', '0.5em', '0.5em'],
                transition: { duration: cfg.buildup + 0.5, ease: ease.out },
              }}
            >
              Promotion incoming
            </motion.div>
          )}

          {/* "RANK UP" banner — crashes in from above */}
          <motion.div
            className="font-black uppercase tracking-[0.4em] select-none"
            style={{
              color: '#fbbf24',
              fontSize: 14 + tier * 2,
              textShadow: '0 0 16px rgba(251, 191, 36, 0.95), 0 2px 10px rgba(0,0,0,0.5)',
            }}
            initial={{ opacity: 0, y: -120, scale: 0.4, rotate: -8 }}
            animate={{
              opacity: 1, y: 0, scale: 1, rotate: 0,
              transition: { duration: 0.55, ease: [0.34, 1.56, 0.64, 1], delay: cfg.buildup + 0.15 },
            }}
          >
            <span className="inline-flex items-center justify-center gap-3">
              <Icon name="star" className="w-[0.9em] h-[0.9em]" />
              {cfg.label}
              <Icon name="star" className="w-[0.9em] h-[0.9em]" />
            </span>
          </motion.div>
        </motion.div>

        {/* CENTER — Icon at viewport center, with rays + rings anchored to it. */}
        <div
          onClick={(e) => e.stopPropagation()}
          className="absolute z-10"
          style={{ top: '50%', left: '50%', transform: 'translate(-50%, -50%)' }}
        >

          {/* Hero icon WRAPPER — relative positioning so the rays + pulse
              rings (children) anchor to the icon's exact centre. Rays and
              rings overflow visually well beyond this 200×200 box thanks
              to overflow: visible. */}
          <motion.div
            className="relative mb-3"
            style={{ width: 200, height: 200 }}
            initial={{ scale: 0, rotate: -40, opacity: 0 }}
            animate={{
              scale:   [0, 1.5 + tier * 0.05, 0.9, 1.08, 1],
              rotate:  [-40, 18, -6, 3, 0],
              opacity: [0, 1, 1, 1, 1],
              transition: { duration: 0.95, ease: ease.out, times: [0, 0.45, 0.7, 0.88, 1], delay: cfg.buildup + 0.3 },
            }}
          >
            {/* Sunburst rays — rebuilt so the rotation PIVOT is at the
                icon's exact centre.

                The outer "anchor" div is a 0×0 box positioned at top:50%/
                left:50% (the parent's centre, which IS the icon's centre)
                with transform-origin:0 0. Its transform: rotate(angle)
                spins the anchor around that single point — no offset, no
                drift.

                The inner span is the actual visible ray, offset outward
                from the anchor by `innerOffset` so opposite rays don't
                overlap at the centre. The ray itself has transform-origin:
                'center top' so its scaleY animation grows OUTWARD from
                the inner edge, not from its middle. */}
            <div
              className="absolute inset-0 pointer-events-none"
              style={{ overflow: 'visible' }}
            >
              {rays.map((r, i) => (
                <div
                  key={`ray-wrap-${i}`}
                  style={{
                    position: 'absolute',
                    top: '50%',
                    left: '50%',
                    width: 0,
                    height: 0,
                    transform: `rotate(${r.angle}deg)`,
                    transformOrigin: '0 0',
                  }}
                >
                  <motion.span
                    style={{
                      position: 'absolute',
                      width: 6,
                      height: '28vh',
                      top: 60,        // innerOffset — tight encase around icon
                      left: -3,       // half-width so ray is centred on the rotation axis
                      transformOrigin: 'center top',
                      background: 'linear-gradient(180deg, rgba(251,191,36,0.85) 0%, rgba(251,191,36,0.4) 35%, rgba(251,191,36,0) 100%)',
                      filter: 'blur(1px)',
                    }}
                    initial={{ opacity: 0, scaleY: 0 }}
                    animate={{
                      opacity: [0, 0.95, 0.6, 0.95],
                      scaleY: [0, 1, 0.9, 1],
                      transition: {
                        duration: 2.4,
                        delay: r.delay,
                        ease: ease.loop,
                        repeat: Infinity,
                        repeatDelay: 0.8,
                      },
                    }}
                  />
                </div>
              ))}
            </div>

            {/* Expanding pulse rings — also anchored to the icon container. */}
            <div
              className="absolute inset-0 flex items-center justify-center pointer-events-none"
              style={{ overflow: 'visible' }}
            >
              {Array.from({ length: cfg.pulseRings }, (_, i) => (
                <motion.div
                  key={`pulse-${i}`}
                  className="absolute rounded-full"
                  style={{
                    width: 120, height: 120,
                    border: '4px solid rgba(251, 191, 36, 0.55)',
                    boxShadow: '0 0 40px rgba(251, 191, 36, 0.6)',
                  }}
                  initial={{ scale: 0, opacity: 0 }}
                  animate={{
                    scale:   [0, 4, 7],
                    opacity: [0, 0.85, 0],
                    transition: { duration: 2.0, ease: ease.loop, delay: cfg.buildup + 0.45 + i * 0.4, repeat: Infinity, repeatDelay: 0.9 },
                  }}
                />
              ))}
            </div>

            {/* The icon itself — centred in the container, ABOVE rays + rings */}
            <div className="absolute inset-0 flex items-center justify-center">
              <motion.div
                className="text-9xl select-none inline-block"
                style={{ filter: `drop-shadow(0 12px 36px ${accent})`, transformOrigin: 'center' }}
                animate={{
                  rotate: [0, -4, 4, -2, 2, 0],
                  scale:  [1, 1.04, 0.98, 1.03, 1],
                }}
                transition={{
                  duration: 3.2, ease: 'easeInOut', repeat: Infinity, delay: cfg.buildup + 1.3,
                }}
              >
                {icon}
              </motion.div>
            </div>
          </motion.div>

        </div>

        {/* BOTTOM REGION — name, subtitle, description, button. Anchored
            to the viewport so its top edge starts just below the icon. */}
        <motion.div
          onClick={(e) => e.stopPropagation()}
          className="absolute left-0 right-0 text-center px-6 z-10"
          style={{ top: '50%', marginTop: 120 }}
          initial="hidden"
          animate="show"
          exit="exit"
          variants={{
            hidden: {},
            show:   { transition: { staggerChildren: 0.07, delayChildren: 0.4 + cfg.buildup } },
            exit:   { opacity: 0, scale: 0.96, y: 8, transition: { duration: dur.sm, ease: ease.out } },
          }}
        >
          {/* New rank name */}
          <motion.div
            className="font-black text-white leading-none mb-3"
            style={{
              fontSize: '3.5rem',
              color: accent,
              textShadow: glow,
              letterSpacing: '-0.02em',
            }}
            variants={burst}
          >
            {name}
          </motion.div>

          <motion.div
            className="text-xs font-black text-white/90 drop-shadow-lg mb-2 uppercase tracking-widest"
            variants={{
              hidden: { opacity: 0, y: 10 },
              show:   { opacity: 1, y: 0, transition: { duration: dur.md, ease: ease.out } },
            }}
          >
            You've levelled up your rank
          </motion.div>

          <motion.p
            className="text-sm text-white/70 mb-6 max-w-xs mx-auto leading-relaxed"
            variants={{
              hidden: { opacity: 0 },
              show:   { opacity: 1, transition: { duration: dur.md, ease: ease.out } },
            }}
          >
            {nextName
              ? <>Next tier: <span className="font-black text-quiz-purple">{nextName}</span> at {xpNext} XP</>
              : <>Top of the cosmic ladder. Legend status.</>}
          </motion.p>

          <motion.button
            onClick={onDismiss}
            className="btn-3d btn-yellow px-8 py-3 text-base pointer-events-auto"
            whileTap={{ scale: 0.95, y: 2 }}
            whileHover={{ y: -1 }}
            transition={ease.squish}
            variants={{
              hidden: { opacity: 0, y: 12 },
              show:   { opacity: 1, y: 0, transition: ease.bouncy },
            }}
          >
            Onwards →
          </motion.button>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
